#!/usr/bin/env bash
set -euo pipefail
set -x

cd "$(dirname "${BASH_SOURCE[0]}")"

cross build --target armv7-unknown-linux-gnueabihf --release

cd bm

cargo deb -v --no-build --target armv7-unknown-linux-gnueabihf --no-strip

