#!/usr/bin/env bash
set -euo pipefail
set -x

cd "$(dirname "${BASH_SOURCE[0]}")"

(cd brew-monitor/www_src && npm i && npm run build)

docker run \
    --rm \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v "$PWD:$PWD" \
    -w "$PWD" \
    -ti \
    brew-monitor/host:latest \
    bash -l -c build-support/build-core
