[workspace]
members = [
  "brew-monitor",
  "lib/bm-bluetooth",
  "lib/bm-tilt",
  "lib/bm-grainfather",
  "lib/bm-beerxml",
  "lib/bm-db",
]

[patch.crates-io]
dht22_pi = { git = 'https://github.com/philipstears/dht22_pi' }
