[workspace]
members = [
  "grainfather-proto",
  "grainfather-control",
  "dht22-monitor",

  "bm-bluetooth",
  "bm-tilt",
  "bm-grainfather",
]

[patch.crates-io]
dht22_pi = { git = 'https://github.com/philipstears/dht22_pi' }
