#!/usr/bin/env bash

curl \
    -vv \
    http://localhost:3030/gf/command \
    -H "Content-Type: application/json" \
    -d '{"type": "UpdateActiveTimer", "data": {"type": "MinutesSeconds", "data": [0, 1]}}'

