[package]
name = "bm"
version = "0.1.0"
authors = ["philipstears <philip@philipstears.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "5.1.1"
enumflags2 = "= 0.6.2"
async-std = { version = "1.4", features = ["attributes"] }
byteorder = "1.3.4"
uuid = "0.8.1"
chrono = "0.4"

bm-bluetooth = { path = "../bm-bluetooth" }
bm-tilt = { path = "../bm-tilt" }


[dependencies.bluez]
git = "https://github.com/laptou/bluez-rs"
branch = "master"
