#!/bin/sh
set -eu

BM_HOME="/var/lib/brew-monitor"
BM_USER="brew-monitor"

create_user() {
    if id "${BM_USER}" > /dev/null 2>&1
    then
        return
    fi

    # Create the system user
    adduser --system --home "${BM_HOME}" --group "${BM_USER}"
}


case "$1" in
configure)
    create_user
    ;;
esac

#DEBHELPER#

